#!/bin/bash

echo "🚀 OpenRole CV & Profile Tools - Complete Deployment Guide"
echo ""
echo "Step 1: Add SSH key to your server"
echo "Run this on your server (hyperdude@145.223.75.73):"
echo ""
echo "mkdir -p ~/.ssh"
echo "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCikqGgF8/SxOlmuQ58YgqsoPSQ19iqdgZCQvIEQyD/OYZ03JlsuUXa7hyJHqxJLkyWnxkOLgBsdbTNT/c4ZCzT++VmX3c1lV9TXi6Tb9usOPARWZpjrKcjJ4b067rc+JlZpiXbLO3b3kPTqHt8hfmXWBSTWi674ucIRyZfmqjgB83ctSkjygz59YlTrz1otTZ4yJWfu7atZmIHkVkXiUCOZFxidSDhky3pmLCd4O4C+uDXtHjVHtSIz1Y2lGE9gNZjCfXlSR5nMwkqDVYYwpN2x/Yc4FP2KDKHMPff+3I3D+RdxlZ2LFgL23nCT2ZqTIyg+BSKDdUb009ikx0e+YlL/Xk2fro7RZX5aVIbBrBxAoBV4CUk840/tSLVCfrFaeQAfRNn64KW9eFT59DuLk7jKEumeddGFZ9JlusCzFAGKDphUcLPv5o/mzu+hnmDEz8j9C7Hwa6BacFKpVC5wHZeBuCXfXVRPf7XFbwfwCGrxQAo5C3ssnJneSq2vbJ3vwia2tgE2udd62W5logSZ0l19d9BKyfHujZXnj7EYMa9gCli5iRozp9GPa7dVT83qyXQVF26wEyWtQaIhf8KKUvRbeEEnPSeUumn7JA+Wh6Sl2uGkL8AnjZYkMsokqEtbIu7I6xG5rUblcGos+5/9uILX66JMnADpXMU32/SWiJTNQ== GitHub Actions OpenRole Deployment' >> ~/.ssh/authorized_keys"
echo "chmod 600 ~/.ssh/authorized_keys"
echo "chmod 700 ~/.ssh"
echo ""
echo "Step 2: Trigger GitHub Actions deployment"
echo "Once SSH key is added, run:"
echo ""
echo "gh workflow run deploy-production.yml --repo aspora-io/openrole"
echo ""
echo "Or visit: https://github.com/aspora-io/openrole/actions/workflows/deploy-production.yml"
echo ""
echo "Step 3: Verify deployment"
echo "After deployment, check:"
echo "- https://openrole.net (Main site)"
echo "- https://api.openrole.net/health (API health)"
echo "- https://api.openrole.net/api/profile/health (CV & Profile Tools)"
echo ""
echo "Features being deployed:"
echo "✅ Complete CV & Profile Tools implementation (58/67 tasks)"
echo "✅ Profile management with privacy controls"
echo "✅ CV generation with multiple templates"
echo "✅ Portfolio showcase with GitHub integration"
echo "✅ PostgreSQL database with Drizzle ORM"
echo "✅ Redis for caching and sessions"
echo "✅ Advanced search and filtering"
echo "✅ GDPR compliant data export/deletion"
echo ""
echo "🎉 Ready to deploy!"