version: '3.8'

services:
  openrole-web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openrole-web.rule=Host(`openrole.net`) || Host(`www.openrole.net`)"
      - "traefik.http.routers.openrole-web.entrypoints=websecure"
      - "traefik.http.routers.openrole-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.openrole-web.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.openrole.net

  openrole-api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openrole-api.rule=Host(`api.openrole.net`)"
      - "traefik.http.routers.openrole-api.entrypoints=websecure"
      - "traefik.http.routers.openrole-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.openrole-api.loadbalancer.server.port=3001"
    environment:
      - NODE_ENV=production

networks:
  traefik:
    external: true