#!/bin/bash

echo "🔑 Setting up SSH key for GitHub Actions deployment"
echo ""
echo "Run this to add the GitHub Actions SSH key to your server:"
echo ""
echo "ssh hyperdude@145.223.75.73"
echo "# Enter password: Bemindful11%"
echo ""
echo "Then run these commands on the server:"
echo ""
echo "mkdir -p ~/.ssh"
echo "chmod 700 ~/.ssh"
echo ""
echo "cat >> ~/.ssh/authorized_keys << 'EOF'"
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCikqGgF8/SxOlmuQ58YgqsoPSQ19iqdgZCQvIEQyD/OYZ03JlsuUXa7hyJHqxJLkyWnxkOLgBsdbTNT/c4ZCzT++VmX3c1lV9TXi6Tb9usOPARWZpjrKcjJ4b067rc+JlZpiXbLO3b3kPTqHt8hfmXWBSTWi674ucIRyZfmqjgB83ctSkjygz59YlTrz1otTZ4yJWfu7atZmIHkVkXiUCOZFxidSDhky3pmLCd4O4C+uDXtHjVHtSIz1Y2lGE9gNZjCfXlSR5nMwkqDVYYwpN2x/Yc4FP2KDKHMPff+3I3D+RdxlZ2LFgL23nCT2ZqTIyg+BSKDdUb009ikx0e+YlL/Xk2fro7RZX5aVIbBrBxAoBV4CUk840/tSLVCfrFaeQAfRNn64KW9eFT59DuLk7jKEumeddGFZ9JlusCzFAGKDphUcLPv5o/mzu+hnmDEz8j9C7Hwa6BacFKpVC5wHZeBuCXfXVRPf7XFbwfwCGrxQAo5C3ssnJneSq2vbJ3vwia2tgE2udd62W5logSZ0l19d9BKyfHujZXnj7EYMa9gCli5iRozp9GPa7dVT83qyXQVF26wEyWtQaIhf8KKUvRbeEEnPSeUumn7JA+Wh6Sl2uGkL8AnjZYkMsokqEtbIu7I6xG5rUblcGos+5/9uILX66JMnADpXMU32/SWiJTNQ== GitHub Actions OpenRole Deployment"
echo "EOF"
echo ""
echo "chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "# Test the key:"
echo "exit"
echo ""
echo "After adding the key, try again:"
echo "gh workflow run deploy-production.yml --repo aspora-io/openrole"